# Generated by Django 2.2 on 2019-04-24 20:50

from django.db import migrations, models
import eye_of_providence.models
import paradiso.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('photo', models.ImageField(storage=paradiso.storage_backends.FaceStorage(), upload_to=eye_of_providence.models.rename_guest_photo)),
                ('external_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('video', models.FileField(storage=paradiso.storage_backends.EventStorage(), upload_to=eye_of_providence.models.rename_event_video)),
                ('guests', models.ManyToManyField(blank=True, to='eye_of_providence.Guest')),
            ],
        ),
    ]
